apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: order-pubsub
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
    - name: connectionString
      value: "amqp://guest:guest@localhost:5672"
    - name: protocol
      value: amqp
    - name: hostname
      value: localhost
    - name: username
      value: guest
    - name: password
      value: guest
    - name: consumerID
      value: cart-service
    - name: durable
      value: "true"
    - name: deletedWhenUnused
      value: "false"
    - name: autoAck
      value: "false"
    - name: deliveryMode
      value: "2"
    - name: requeueInFailure
      value: "true"
    - name: prefetchCount
      value: "10"
    - name: reconnectWait
      value: "5"
    - name: concurrencyMode
      value: parallel
scopes:
  - cart-service
